Booth/urls.py
from django.urls import path

from Booth import views

urlpatterns = [
    path('booth/<int:booth_id>/', views.booth, name='booth'),
    path('refresh_data/', views.refresh_data, name='refresh_data'),
    path('create_booth_application/', views.create_booth_application, name='create_booth_application'),
    path('cancel_booth/<int:booth_id>/', views.cancel_booth, name='cancel_booth')
]

COMP3030J_Hudson/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from django.views.generic import RedirectView
from Inventory.views import *
from Layout.views import *
from Statistic.views import *
from System.views import *
from User.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# 当settings.py的DEBUG为True时, handler404不会生效, 因为Django要暴露错误信息以方便开发者调试
handler404 = 'System.views.custom_404_interceptor'  # 该行代码用于无效页面的重定向

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='User:welcome', permanent=False)),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('Inventory/', include(('Inventory.urls', 'Inventory'), namespace='Inventory')),
    path('Layout/', include(('Layout.urls', 'Layout'), namespace='Layout')),
    path('Statistic/', include(('Statistic.urls', 'Statistic'), namespace='Statistic')),
    path('System/', include(('System.urls', 'System'), namespace='System')),
    path('User/', include(('User.urls', 'User'), namespace='User')),
    path('Venue/', include(('Venue.urls', 'Venue'), namespace='Venue')),
    path('Exhibition/', include(('Exhibition.urls', 'Exhibition'), namespace='Exhibition')),
    path('Booth/', include(('Booth.urls', 'Booth'), namespace='Booth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 添加data/的url映射
    urlpatterns += staticfiles_urlpatterns()  # 添加static/的url映射

Inventory/urls.py
from django.urls import path
from . import views
from .views import (category_detail_view, edit_inventory_category, delete_inventory_category, edit_item, return_item,
                    delete_item)

urlpatterns = [
    path('inventory/<str:space_type>/<int:space_id>/', views.inventory, name='inventory'),
    #path('inventory/<str:current_access_type>/<int:current_access_id>/', views.inventory, name='inventory'),
    path('create_res_application', views.create_res_application, name='create_res_application'),
    path('category/<int:category_id>/details/', category_detail_view, name='category_detail'),
    path('edit-category/<int:category_id>/', edit_inventory_category, name='edit-category'),
    path('delete-category/<int:category_id>/', delete_inventory_category, name='delete-category'),
    path('item/<int:item_id>/edit/', edit_item, name='edit_item'),
    path('item/<int:item_id>/return/', views.return_item, name='return_item'),
    path('item/<int:item_id>/delete/', views.delete_item, name='delete_item'),
    path('refresh_data/', views.refresh_data, name='refresh_data'),
]

Layout/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('layout/', views.layout, name='layout'),
    path('refresh_data/', views.refresh_data, name='refresh_data'),
    path('add_sublayer/', views.add_sublayer, name='add_sublayer'),
    path('delete_layer/', views.delete_layer, name='delete_layer'),
    path('edit_layer/', views.edit_layer, name='edit_layer'),
    path('add_element/', views.add_element, name='add_element'),
    path('edit_element/', views.edit_element, name='edit_element'),
    path('delete_element/', views.delete_element, name='delete_element'),
    path('synchronize_elements_data/', views.synchronize_elements_data, name='synchronize_elements_data'),
]

Statistic/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('statistic/', views.statistic, name='statistic'),
    path('get_consumption_data/<int:year>/', views.get_consumption_data, name='get_consumption_data'),
    path('get_venues/', views.get_venues, name='get_venues'),
    path('get_consumption_data_by_venue/<str:venue_name>/<int:year>/', views.get_consumption_data_by_venue, name='get_consumption_data_by_venue'),

    path('monitor_venue/', views.monitor_venue, name='monitor_venue'),
    path('monitor/query_flow_by_day/', views.query_flow_by_day, name='query_flow_by_day'),
    path('recognize_flow/', views.recognize_flow, name='recognize_flow'),
    path('monitor/capture/<int:monitor_id>/', views.capture, name='capture'),
    path('refresh_data/', views.refresh_data, name='refresh_data'),
    path('synchronize_monitors_data/', views.synchronize_monitors_data, name='synchronize_monitors_data'),
    path('add_monitor/', views.add_monitor, name='add_monitor'),
    path('edit_monitor/', views.edit_monitor, name='edit_monitor'),
    path('delete_monitor/', views.delete_monitor, name='delete_monitor'),

    path('add_simulated_data/', views.add_simulated_data, name='add_simulated_data'),
]

User/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('welcome/', views.welcome, name='welcome'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('message/', views.view_message, name='view_message'),
    path('message/detail/<int:message_id>/', views.view_message_detail, name='view_message_detail'),
    path('message/reply_message/<int:message_id>/', views.reply_message, name='reply_message'),
    path('application/detail/<str:application_type>/<int:application_id>/',
         views.view_application_detail, name='view_application_detail'),
    path('application/reject_application/<str:application_type>/<int:application_id>/',
         views.reject_application, name='reject_application'),
    path('application/accept_application/<str:application_type>/<int:application_id>/',
         views.accept_application, name='accept_application'),
]

Venue/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('modify_venue/<int:venue_id>', views.modify_venue, name='modify_venue'),
    path('delete_venue/<int:venue_id>', views.delete_venue, name='delete_venue'),
    path('venue/<int:venue_id>', views.venue, name='venue'),
    path('refresh_data/', views.refresh_data, name='refresh_data'),
]

Booth/models.py
import os
import uuid
from django.conf import settings
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from User.models import Application


class Booth(models.Model):
    def booth_upload_to(instance, filename):  # 即使不使用filename参数,也必须保留, 这是Django的硬性要求
        # 获取文件的扩展名
        extension = filename.split('.')[-1]
        # 生成一个新的UUID文件名
        new_filename = '{0}.{1}'.format(uuid.uuid4(), extension)
        return 'Booth/{0}'.format(new_filename)

    def save(self, *args, **kwargs):
        if self.pk:  # 如果模型已经存在，则是更新过程
            old_venue = Booth.objects.get(pk=self.pk)
            if old_venue.image and old_venue.image != self.image:
                if os.path.isfile(old_venue.image.path):
                    os.remove(old_venue.image.path)  # 删除旧图片
        # 保存图片到新的路径
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):  # 重写了delete方法,使得删除前能够移除图片文件
        # 删除相关图片文件
        if self.image:
            if os.path.isfile(self.image.path):
                os.remove(self.image.path)
        super().delete(*args, **kwargs)

    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    exhibitor = models.ForeignKey("User.Exhibitor", on_delete=models.CASCADE, related_name='booths')
    exhibition = models.ForeignKey("Exhibition.Exhibition", on_delete=models.CASCADE, related_name='booths')
    sectors = GenericRelation('Layout.SpaceUnit', content_type_field='affiliation_content_type',
                              object_id_field='affiliation_object_id')
    start_at = models.DateTimeField()
    end_at = models.DateTimeField()
    items = GenericRelation('Inventory.Item', content_type_field='affiliation_content_type',
                            object_id_field='affiliation_object_id')  # items = List<Item>, 由Django ORM的反向关系实现
    inventory_categories = GenericRelation('Inventory.InventoryCategory',
                                           content_type_field='origin_content_type',
                                           object_id_field='origin_object_id')
    # resource_applications : List<ResourceApplication>, 由Django ORM的反向关系实现
    image = models.ImageField(upload_to=booth_upload_to, null=True, blank=True)


class BoothApplication(Application):
    # 更改related_name，避免与其它application冲突
    applicant = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                  related_name='booth_applications')
    # 某个展台被删除后，申请同时被删除
    booth = models.OneToOneField("Booth", on_delete=models.CASCADE, null=True,
                                      related_name='booth_application')
    # 某个消息被删除后，申请不会被删除
    message_details = GenericRelation("User.MessageDetail", related_query_name='booth_application', null=True,
                                      content_type_field='application_content_type',
                                      object_id_field='application_object_id')

Booth/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseNotAllowed, JsonResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone
from rest_framework import status
from Booth.forms import BoothApplicationForm
from Booth.models import Booth, BoothApplication
from Layout.serializers import SpaceUnitSerializer
from User.models import Application


@login_required
def booth(request, booth_id):
    if request.method == 'GET':
        print(booth_id)
        current_booth = Booth.objects.filter(id=booth_id).first()
        if current_booth is None:
            exhibition_id = request.session.get('exhibition_id', None)
            if exhibition_id:
                return redirect('Exhibition:exhibition', exhibition_id=exhibition_id)
            else:
                return redirect('Venue:home')
        request.session['booth_id'] = booth_id  # 将booth_id存入session
        application = current_booth.booth_application
        if application.stage == Application.Stage.CANCELLED or application.stage == Application.Stage.REJECTED:
            return redirect('Exhibition:exhibition', exhibition_id=current_booth.exhibition.pk)

        # 判断当前是否为展览的拥有者(管理员，申请者或该展览的举办方)
        user_type = request.session.get('user_type', '')
        if (user_type != 'Manager'
                and request.user != current_booth.exhibition.organizer.detail
                and request.user != application.applicant):
            is_owner = False
        else:
            is_owner = True

        return render(request, 'System/booth.html', {
            'booth': current_booth,
            'sectors':  current_booth.sectors.filter(inherit_from__isnull=False).order_by('created_at'),
            'is_owner': is_owner,
            'user_type': user_type,
        })
    else:
        return HttpResponseNotAllowed(['GET'])


def refresh_data(request):
    if request.method == 'GET':
        # 从GET请求中获取参数
        sector_id = int(request.GET.get('sector_id', 0))
        booth_id = int(request.GET.get('booth_id', 0))
        user_type = request.GET.get('user_type')
        # 验证数据有效性
        if (sector_id is None) or (booth_id is None) or (user_type not in ['Manager', 'Organizer', 'Exhibitor']):
            return JsonResponse({'error': 'Invalid request'}, status=400)
        current_exhibition = get_object_or_404(Booth, pk=booth_id)
        if sector_id == 0:  # 说明当前请求时用户初次进入展览页面, 返回当前展会的第一个Sector
            sector_id = current_exhibition.sectors.first().id
        # 获取当前场馆的当前楼层的Root SpaceUnit节点(parent_unit=None 且创建时间最早)
        root = current_exhibition.sectors.filter(pk=sector_id).order_by('created_at').first()
        # 返回JSON化的root数据
        if root is not None:
            # 使用Serializer序列化root
            serializer = SpaceUnitSerializer(root)
            return JsonResponse(serializer.data)  # 使用Django的JsonResponse返回数据
        else:
            return JsonResponse({'error': 'No root SpaceUnit found for the specified floor'},
                                status=status.HTTP_404_NOT_FOUND)
    else:
        return JsonResponse({'error': 'Invalid request'}, status=status.HTTP_400_BAD_REQUEST)


@login_required
def create_booth_application(request):
    if request.method == 'POST':
        form = BoothApplicationForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                form.create_application(request)
                return JsonResponse({'success': 'Booth application created successfully!'}, status=200)
            except Exception as e:
                print(e)
                return JsonResponse({'error': 'Internal server error.', 'details': str(e)}, status=500)
        else:
            first_error_key, first_error_messages = list(form.errors.items())[0]
            first_error_message = f"{first_error_key}: {first_error_messages[0]}"
            return JsonResponse({'error': first_error_message}, status=400)
    else:
        return HttpResponseNotAllowed(['POST'])


@login_required
def cancel_booth(request, booth_id):
    if request.method == 'POST':
        booth = Booth.objects.filter(id=booth_id).first()
        application = BoothApplication.objects.filter(booth_id=booth_id).first()
        if booth_id is None or application is None:
            return JsonResponse({'error': 'Booth not found'}, status=404)

        # 自动结束，展览结束时间已经过了
        if booth.end_at < timezone.now():
            pass
        # 手动取消，管理员强制取消，或申请处于初始提交阶段
        elif hasattr(request.user, 'manager') or application.stage == Application.Stage.INITIAL_SUBMISSION:
            application.stage = Application.Stage.CANCELLED
            application.save()
        else:
            return JsonResponse({'error': 'Exhibition application cannot be canceled at this stage'}, status=400)

        # 删除展台申请关联的sector
        for sector in booth.sectors.all():
            sector.delete()

        # 归还全部物品
        for item in booth.items.all():
            if item.affiliation != item.category.origin:
                item.affiliation_content_type = ContentType.objects.get_for_model(item.category.origin)
                item.affiliation_object_id = item.category.origin.pk
                item.is_using = 0
                item.save()
        for category in booth.inventory_categories.all():
            category.delete()
        return JsonResponse({'success': 'Booth application canceled successfully!'}, status=200)
    else:
        return HttpResponseNotAllowed(['POST'])

templates/Booth/booth.html
{% extends 'Public/base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}

{% block extra_head %}
    <title>Booth</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.min.js"></script>
    <script src="https://unpkg.com/konva@9/konva.min.js"></script>

    <link rel="stylesheet" href="{% static 'css/Booth/booth.css' %}">
{% endblock %}

{% block extra_nav_icons %}
    <!-- 导航栏额外按键-->
    {% if user.is_authenticated and user_type == 'Manager' %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Statistic:statistic' %}"><i class="fas fa-chart-bar"></i>
                Statistics</a>
        </li>
    {% endif %}
    {% if user.is_authenticated and user_type != 'Guest' %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Layout:layout' %}"><i class="fas fa-edit"></i> Layout</a>
        </li>
    {% endif %}
{% endblock %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'Venue:home' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'Venue:venue' booth.exhibition.venue.id %}">{{ booth.exhibition.venue.name }}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'Exhibition:exhibition' booth.exhibition.id %}">{{ booth.exhibition.name }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ booth.name }}</li>
        </ol>
    </nav>
{% endblock %}

{% block content %}
    <div id="booth-app">

        <div class="d-flex justify-content-between align-items-center mb-3" id="booth-header">
            <div id="booth-name" class="booth-text logo-title">
                Current Booth: {{ booth.name }}
            </div>
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownFloorMenu"
                        data-bs-toggle="dropdown" aria-expanded="false">
                    Current Sector: [[ layers.length > 0 ? layers[0].name : 'Loading...' ]]
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownFloorMenu">
                    {% for sector in sectors %}
                        {% comment %}你先别急, 这里是Pycharm的模板语法出现了问题, 这里其实是可以正常运行的{% endcomment %}
                        <li><a class="dropdown-item" href="#" @click="toggleSector({{ sector.pk }})">Sector {{ sector.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div id="konva-container"></div>
        <!-- 用于展示在画板上选中的KonvaElement所在的Layer -->
        <div id="tooltip"
             style="position: absolute; display: none; background: lightgrey; padding: 5px; border-radius: 3px;"></div>

        <!-- Floating Action Button -->
        {% if user.is_authenticated and user_type == 'Exhibitor' %}
            <a class="btn btn-success rounded-circle shadow"
               style="position: fixed; bottom: 100px; right: 10px; z-index: 1040; width: 60px; height: 60px; display: flex; justify-content: center; align-items: center; font-size: 30px;"
               href="{% url 'Inventory:inventory' 'booth' booth.id %}" title="View Inventory">
                📦
            </a>
        {% endif %}

    </div>
{% endblock %}

{% block scripts %}
    <script>
        new Vue({
            el: '#booth-app',
            delimiters: ['[[', ']]'], // 更改Vue的插值表达式定界符
            data: {
                layers: [],
                stage: null,
                currentElement: null,
            },
            mounted() {
                this.refreshData(0);
            },
            beforeDestroy() {
                if (this.stage) {
                    this.stage.container().removeEventListener('wheel', this.handleWheelZoom);
                }
                window.removeEventListener('resize', this.handleResize);
            },
            methods: {
                // ----------------- 数据加载 -----------------
                refreshData(sectorId) {
                    console.log('Refreshing data...');
                    return axios.get('{% url "Booth:refresh_data" %}', {
                        params: {
                            sector_id: sectorId,
                            booth_id: {{ booth.id }},
                            user_type: '{{ user_type }}',
                        }
                    }).then(response => {
                        if (response.data && response.data.id) {
                            console.log('Data synchronized:', response.data);
                            this.layers = []; // 清空Vue实例的layers数组
                            this.layers = [response.data];
                            this.renderKonva(); // 重新初始化Konva
                        } else {
                            console.error('Unexpected response data:', response.data);
                        }
                    }).catch(error => {
                        console.error('Failed to synchronize data:', error);
                    });
                },

                // ----------------- 以下是与konva.js相关的函数 -----------------

                // ----------------- konva.js: 加载数据 -----------------
                renderKonva() {
                    console.log('Rendering Konva...');
                    this.stage = new Konva.Stage({
                        container: 'konva-container',
                        width: window.innerWidth * 0.9,
                        height: window.innerHeight * 0.9,
                    });

                    // 添加滚轮缩放事件监听器
                    this.stage.container().addEventListener('wheel', this.handleWheelZoom);
                    // 添加窗口大小变化事件监听器
                    window.addEventListener('resize', this.handleResize);
                    // 添加画板拖拽的监听器
                    this.stage.on('mousedown', this.handleMouseDown);
                    this.stage.on('mouseup', this.handleMouseUp);
                    this.stage.on('mousemove', this.handleMouseMove);
                    
                    const loadImage = (url, nodeData, group, element, spaceUnit) => { // 保证图片的同步而非异步加载, 这样能够避免图层的乱序
                        return new Promise((resolve, reject) => {
                            Konva.Image.fromURL(url, (imageNode) => {
                                try {
                                    imageNode.setAttrs(nodeData);
                                    group.add(imageNode);
                                    this.addListenersForElement(imageNode, element, spaceUnit);
                                    resolve(imageNode);
                                } catch (error) {
                                    reject(error);
                                }
                            });
                        });
                    };

                    // 递归函数来处理每个层级的SpaceUnit和elements
                    const processLayer = async (spaceUnits, parent) => {
                        for (const spaceUnit of spaceUnits) {
                            // 使用Group来模拟层嵌套
                            let group = new Konva.Group();
                            parent.add(group); // 将当前层添加到父组件中

                            // 处理当前SpaceUnit的elements
                            for (const element of spaceUnit.elements) {
                                const nodeData = JSON.parse(element.data);
                                if (element.type === 'Image') { // 如果加载的是图片
                                    await loadImage(element.image, nodeData, group, element, spaceUnit);
                                } else {
                                    const node = Konva.Node.create(nodeData, group);
                                    group.add(node);
                                    this.addListenersForElement(node, element, spaceUnit); // 添加变换和拖拽结束的事件监听器
                                }
                            }

                            // 如果当前SpaceUnit有子单位，则递归处理
                            if (spaceUnit.child_units && spaceUnit.child_units.length > 0) {
                                await processLayer(spaceUnit.child_units, parent);
                            }
                        }
                    };

                    const rootLayer = new Konva.Layer();
                    this.stage.add(rootLayer);
                    processLayer(this.layers, rootLayer); // 从根层级开始处理所有层级
                    rootLayer.draw();
                },

                addListenersForElement(node, element, parentSpaceUnit) {
                    // 添加右键点击监听器
                    node.on('contextmenu', (e) => {
                        e.evt.preventDefault();
                        let element = this.findElementByKonvaId(this.layers, node.id());
                        if (element) {
                            this.currentElement = element;
                            // TODO 可在此处设置右键画板上的Konva Element后的操作(比如弹出模态框并给模态框的表单赋值)
                        }
                    });

                    const tooltip = document.getElementById('tooltip');
                    const showTooltip = (text, evt) => {
                        tooltip.style.display = 'block';
                        tooltip.innerText = text;
                        tooltip.style.backgroundColor = parentSpaceUnit.available ? 'green' : 'red'; // 根据 Available 属性设置背景色
                        const mousePos = this.stage.getPointerPosition();
                        tooltip.style.top = `${mousePos.y + 5}px`;
                        tooltip.style.left = `${mousePos.x + 5}px`;
                    };
                    const hideTooltip = () => {
                        tooltip.style.display = 'none';
                    };

                    // 添加鼠标悬浮事件监听器
                    node.on('mouseenter', (evt) => showTooltip(parentSpaceUnit.name, evt));
                    node.on('mouseleave', hideTooltip);
                    node.on('mousemove', (evt) => showTooltip(parentSpaceUnit.name, evt));
                },

                findElementByKonvaId(layers, elementId) {
                    for (let layer of layers) {
                        for (let element of layer.elements) {
                            if (String(element.id) === String(elementId)) {
                                return element;
                            }
                        }
                        if (layer.child_units) {
                            let found = this.findElementByKonvaId(layer.child_units, elementId);
                            if (found) return found;
                        }
                    }
                    return null;
                },

                // ----------------- konva.js: 控制Stage上的交互事件 -----------------

                handleMouseDown(e) {
                    // 确保是左键点击
                    if (e.evt.button === 0) {
                        this.isDragging = true;
                        this.lastPointerPosition = this.stage.getPointerPosition();
                    }
                },

                handleMouseUp() {
                    this.isDragging = false; // 停止拖动
                },

                handleMouseMove(e) {
                    if (this.isDragging) {
                        // 计算移动距离
                        const pointerPosition = this.stage.getPointerPosition();
                        const dx = pointerPosition.x - this.lastPointerPosition.x;
                        const dy = pointerPosition.y - this.lastPointerPosition.y;

                        // 更新位置
                        this.stage.x(this.stage.x() + dx);
                        this.stage.y(this.stage.y() + dy);

                        // 更新最后的指针位置
                        this.lastPointerPosition = pointerPosition;

                        // 重新渲染
                        this.stage.batchDraw();
                    }
                },

                handleWheelZoom(event) {
                    // 检查是否按下了Ctrl键
                    if (event.ctrlKey) {
                        event.preventDefault();

                        const oldScale = this.stage.scaleX();
                        const pointer = this.stage.getPointerPosition();

                        // 放大或缩小
                        const scaleBy = 1.1;
                        const newScale = event.deltaY > 0 ? oldScale / scaleBy : oldScale * scaleBy;

                        this.stage.scale({x: newScale, y: newScale});

                        const mousePointTo = {
                            x: (pointer.x - this.stage.x()) / oldScale,
                            y: (pointer.y - this.stage.y()) / oldScale,
                        };

                        const newPos = {
                            x: pointer.x - mousePointTo.x * newScale,
                            y: pointer.y - mousePointTo.y * newScale,
                        };

                        this.stage.position(newPos);
                        this.stage.batchDraw();
                    }
                },

                handleStageClick(e) {
                    if (e.evt.button === 2) { // Right-click to finish polygon drawing
                        e.evt.preventDefault(); // 阻止默认上下文菜单
                        //this.resetState();
                    }
                },

                handleResize() {
                    const width = window.innerWidth * 0.9;
                    const height = window.innerHeight * 0.91;
                    this.stage.size({width, height});
                },

                // ----------------- 其他函数 -----------------

                toggleSector(sectorId) { // 切换楼层
                    if (this.layers[0].id !== sectorId) {
                        this.refreshData(sectorId);
                    }
                },
            
            }
        });

    </script>
{% endblock %}