Booth/urls.py
from django.urls import path

from Booth import views

urlpatterns = [
    path('booth/<int:booth_id>/', views.booth, name='booth'),
    path('refresh_data/', views.refresh_data, name='refresh_data'),
    path('create_booth_application/', views.create_booth_application, name='create_booth_application'),
    path('cancel_booth/<int:booth_id>/', views.cancel_booth, name='cancel_booth')
]

COMP3030J_Hudson/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from django.views.generic import RedirectView
from Inventory.views import *
from Layout.views import *
from Statistic.views import *
from System.views import *
from User.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# 当settings.py的DEBUG为True时, handler404不会生效, 因为Django要暴露错误信息以方便开发者调试
handler404 = 'System.views.custom_404_interceptor'  # 该行代码用于无效页面的重定向

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='User:welcome', permanent=False)),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('Inventory/', include(('Inventory.urls', 'Inventory'), namespace='Inventory')),
    path('Layout/', include(('Layout.urls', 'Layout'), namespace='Layout')),
    path('Statistic/', include(('Statistic.urls', 'Statistic'), namespace='Statistic')),
    path('System/', include(('System.urls', 'System'), namespace='System')),
    path('User/', include(('User.urls', 'User'), namespace='User')),
    path('Venue/', include(('Venue.urls', 'Venue'), namespace='Venue')),
    path('Exhibition/', include(('Exhibition.urls', 'Exhibition'), namespace='Exhibition')),
    path('Booth/', include(('Booth.urls', 'Booth'), namespace='Booth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 添加data/的url映射
    urlpatterns += staticfiles_urlpatterns()  # 添加static/的url映射

System/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('copilot/', views.copilot, name='copilot'),
    path('delete_all_conversation_history/', views.delete_all_conversation_history, name='delete_all_conversation_history'),

]

User/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('welcome/', views.welcome, name='welcome'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('message/', views.view_message, name='view_message'),
    path('message/detail/<int:message_id>/', views.view_message_detail, name='view_message_detail'),
    path('message/reply_message/<int:message_id>/', views.reply_message, name='reply_message'),
    path('application/detail/<str:application_type>/<int:application_id>/',
         views.view_application_detail, name='view_application_detail'),
    path('application/reject_application/<str:application_type>/<int:application_id>/',
         views.reject_application, name='reject_application'),
    path('application/accept_application/<str:application_type>/<int:application_id>/',
         views.accept_application, name='accept_application'),
]

Venue/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('modify_venue/<int:venue_id>', views.modify_venue, name='modify_venue'),
    path('delete_venue/<int:venue_id>', views.delete_venue, name='delete_venue'),
    path('venue/<int:venue_id>', views.venue, name='venue'),
    path('refresh_data/', views.refresh_data, name='refresh_data'),
]

Booth/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseNotAllowed, JsonResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone
from rest_framework import status
from Booth.forms import BoothApplicationForm
from Booth.models import Booth, BoothApplication
from Layout.serializers import SpaceUnitSerializer
from User.models import Application


@login_required
def booth(request, booth_id):
    if request.method == 'GET':
        print(booth_id)
        current_booth = Booth.objects.filter(id=booth_id).first()
        if current_booth is None:
            exhibition_id = request.session.get('exhibition_id', None)
            if exhibition_id:
                return redirect('Exhibition:exhibition', exhibition_id=exhibition_id)
            else:
                return redirect('Venue:home')
        request.session['booth_id'] = booth_id  # 将booth_id存入session
        application = current_booth.booth_application
        if application.stage == Application.Stage.CANCELLED or application.stage == Application.Stage.REJECTED:
            return redirect('Exhibition:exhibition', exhibition_id=current_booth.exhibition.pk)

        # 判断当前是否为展览的拥有者(管理员，申请者或该展览的举办方)
        user_type = request.session.get('user_type', '')
        if (user_type != 'Manager'
                and request.user != current_booth.exhibition.organizer.detail
                and request.user != application.applicant):
            is_owner = False
        else:
            is_owner = True

        return render(request, 'System/booth.html', {
            'booth': current_booth,
            'sectors':  current_booth.sectors.filter(inherit_from__isnull=False).order_by('created_at'),
            'is_owner': is_owner,
            'user_type': user_type,
        })
    else:
        return HttpResponseNotAllowed(['GET'])


def refresh_data(request):
    if request.method == 'GET':
        # 从GET请求中获取参数
        sector_id = int(request.GET.get('sector_id', 0))
        booth_id = int(request.GET.get('booth_id', 0))
        user_type = request.GET.get('user_type')
        # 验证数据有效性
        if (sector_id is None) or (booth_id is None) or (user_type not in ['Manager', 'Organizer', 'Exhibitor']):
            return JsonResponse({'error': 'Invalid request'}, status=400)
        current_exhibition = get_object_or_404(Booth, pk=booth_id)
        if sector_id == 0:  # 说明当前请求时用户初次进入展览页面, 返回当前展会的第一个Sector
            sector_id = current_exhibition.sectors.first().id
        # 获取当前场馆的当前楼层的Root SpaceUnit节点(parent_unit=None 且创建时间最早)
        root = current_exhibition.sectors.filter(pk=sector_id).order_by('created_at').first()
        # 返回JSON化的root数据
        if root is not None:
            # 使用Serializer序列化root
            serializer = SpaceUnitSerializer(root)
            return JsonResponse(serializer.data)  # 使用Django的JsonResponse返回数据
        else:
            return JsonResponse({'error': 'No root SpaceUnit found for the specified floor'},
                                status=status.HTTP_404_NOT_FOUND)
    else:
        return JsonResponse({'error': 'Invalid request'}, status=status.HTTP_400_BAD_REQUEST)


@login_required
def create_booth_application(request):
    if request.method == 'POST':
        form = BoothApplicationForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                form.create_application(request)
                return JsonResponse({'success': 'Booth application created successfully!'}, status=200)
            except Exception as e:
                print(e)
                return JsonResponse({'error': 'Internal server error.', 'details': str(e)}, status=500)
        else:
            first_error_key, first_error_messages = list(form.errors.items())[0]
            first_error_message = f"{first_error_key}: {first_error_messages[0]}"
            return JsonResponse({'error': first_error_message}, status=400)
    else:
        return HttpResponseNotAllowed(['POST'])


@login_required
def cancel_booth(request, booth_id):
    if request.method == 'POST':
        booth = Booth.objects.filter(id=booth_id).first()
        application = BoothApplication.objects.filter(booth_id=booth_id).first()
        if booth_id is None or application is None:
            return JsonResponse({'error': 'Booth not found'}, status=404)

        # 自动结束，展览结束时间已经过了
        if booth.end_at < timezone.now():
            pass
        # 手动取消，管理员强制取消，或申请处于初始提交阶段
        elif hasattr(request.user, 'manager') or application.stage == Application.Stage.INITIAL_SUBMISSION:
            application.stage = Application.Stage.CANCELLED
            application.save()
        else:
            return JsonResponse({'error': 'Exhibition application cannot be canceled at this stage'}, status=400)

        # 删除展台申请关联的sector
        for sector in booth.sectors.all():
            sector.delete()

        # 归还全部物品
        for item in booth.items.all():
            if item.affiliation != item.category.origin:
                item.affiliation_content_type = ContentType.objects.get_for_model(item.category.origin)
                item.affiliation_object_id = item.category.origin.pk
                item.is_using = 0
                item.save()
        for category in booth.inventory_categories.all():
            category.delete()
        return JsonResponse({'success': 'Booth application canceled successfully!'}, status=200)
    else:
        return HttpResponseNotAllowed(['POST'])

Exhibition/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.http import JsonResponse, HttpResponseNotAllowed
from django.shortcuts import redirect, render, get_object_or_404
from rest_framework import status
from django.utils import timezone

from Booth.forms import BoothApplicationForm, FilterBoothsForm
from Booth.views import cancel_booth
from Exhibition.forms import ExhibApplicationForm
from Exhibition.models import Exhibition, ExhibitionApplication
from Layout.serializers import SpaceUnitSerializer
from django.contrib import messages

from User.models import Application


@login_required
def exhibition(request, exhibition_id):
    current_exhibition = Exhibition.objects.filter(id=exhibition_id).first()
    if current_exhibition is None:
        venue_id = request.session.get('venue_id', None)
        if venue_id:
            return redirect('Venue:venue', venue_id=venue_id)
        else:
            return redirect('Venue:home')
    request.session['exhibition_id'] = exhibition_id  # 将exhibition_id存入session
    application = current_exhibition.exhibition_application
    if application.stage == Application.Stage.CANCELLED or application.stage == Application.Stage.REJECTED:
        return redirect('Venue:venue', venue_id=current_exhibition.venue.pk)

    # 判断当前是否为展览的拥有者
    user_type = request.session.get('user_type', '')
    if user_type == 'Manager' or request.user == application.applicant:
        is_owner = True
    else:
        is_owner = False

    booths = None
    if request.method == 'GET':
        # 筛选end_at在今日或者今日之后的展台,并按照从最近开始到最远开始的顺序排序
        booths = current_exhibition.booths.filter(start_at__lte=timezone.now()).order_by('-start_at')
    elif request.method == 'POST':
        submitted_filter_form = FilterBoothsForm(request.POST)
        if submitted_filter_form.is_valid():
            booths = submitted_filter_form.filter()
            messages.success(request, 'Filter exhibitions success!')
        else:
            first_error_key, first_error_messages = list(submitted_filter_form.errors.items())[0]
            first_error_message = first_error_key + ': ' + first_error_messages[0]
            return JsonResponse({'error': first_error_message}, status=400)

    # 将展区信息转换为字典
    booth_list = []
    for booth in booths:
        sectors = ''
        for sector in booth.sectors.all():
            if sector.inherit_from is not None:
                sectors += sector.name + ' '
        stage = booth.booth_application.get_stage_display()

        if stage == 'REJECTED' or stage == 'CANCELLED':  # 展览申请被拒绝(不显示)
            continue
        elif stage == 'ACCEPTED':
            stage = '✅ ACCEPTED'
            if booth.end_at < timezone.now():  # 展览已结束
                stage = '🔴 OUTDATED'
            elif booth.start_at < timezone.now() < booth.end_at:  # 展览进行中
                stage = '🟢 UNDERWAY'
        elif stage == 'INITIAL_SUBMISSION':
            stage = '🟠 PENDING'
        else:
            continue
        booth_list.append({
            'id': booth.id,
            'name': booth.name,
            'description': booth.description,
            'image': booth.image.url,
            'start_at': booth.start_at,
            'end_at': booth.end_at,
            'exhibitor': booth.exhibitor.detail.username,
            'sectors': sectors,
            'stage': stage
        })

    return render(request, 'System/exhibition.html', {
        'exhibition': current_exhibition,
        'booths': booth_list,
        'sectors': current_exhibition.sectors.filter(inherit_from__isnull=False).order_by('created_at'),
        'is_owner': is_owner,
        'user_type': user_type,
        'filter_form': FilterBoothsForm(),
        'application_form': BoothApplicationForm(
            initial={'affiliation_content_type': ContentType.objects.get_for_model(current_exhibition),
                     'affiliation_object_id': exhibition_id}),
    })


def refresh_data(request):
    if request.method == 'GET':
        # 从GET请求中获取参数
        sector_id = int(request.GET.get('sector_id', 0))
        exhibition_id = int(request.GET.get('exhibition_id', 0))
        user_type = request.GET.get('user_type')
        # 验证数据有效性
        if (sector_id is None) or (exhibition_id is None) or (user_type not in ['Manager', 'Organizer', 'Exhibitor']):
            return JsonResponse({'error': 'Invalid request'}, status=400)
        current_exhibition = get_object_or_404(Exhibition, pk=exhibition_id)
        if sector_id == 0:  # 说明当前请求时用户初次进入展览页面, 返回当前展会的第一个Sector
            sector_id = current_exhibition.sectors.first().id
        # 获取当前场馆的当前楼层的Root SpaceUnit节点(parent_unit=None 且创建时间最早)
        root = current_exhibition.sectors.filter(pk=sector_id).order_by('created_at').first()
        # 返回JSON化的root数据
        if root is not None:
            # 使用Serializer序列化root
            serializer = SpaceUnitSerializer(root)
            return JsonResponse(serializer.data)  # 使用Django的JsonResponse返回数据
        else:
            return JsonResponse({'error': 'No root SpaceUnit found for the specified floor'},
                                status=status.HTTP_404_NOT_FOUND)
    else:
        return JsonResponse({'error': 'Invalid request'}, status=status.HTTP_400_BAD_REQUEST)


# 创建展览申请
@login_required
def create_exhibit_application(request):
    if request.method == 'POST':
        form = ExhibApplicationForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                form.create_application(request)
                return JsonResponse({'success': 'Exhibition application created successfully!'}, status=200)
            except Exception as e:
                print(e)
                return JsonResponse({'error': 'Internal Server Error', 'details': str(e)}, status=500)
        else:
            first_error_key, first_error_messages = list(form.errors.items())[0]
            first_error_message = first_error_key + ': ' + first_error_messages[0]
            return JsonResponse({'error': first_error_message}, status=400)
    else:
        return HttpResponseNotAllowed(['POST'])


# 取消操作包括手动取消申请和自动结束
@login_required
def cancel_exhibition(request, exhibition_id):
    if request.method == 'POST':
        exhibition = Exhibition.objects.filter(id=exhibition_id).first()
        application = ExhibitionApplication.objects.filter(exhibition_id=exhibition_id).first()
        if exhibition_id is None or application is None:
            return JsonResponse({'error': 'Exhibition not found'}, status=404)

        # 自动结束，展览结束时间已经过了
        if exhibition.end_at < timezone.now():
            pass
        # 手动取消，管理员强制取消，或申请处于初始提交阶段
        elif hasattr(request.user, 'manager') or application.stage == Application.Stage.INITIAL_SUBMISSION:
            application.stage = Application.Stage.CANCELLED
            application.save()
        else:
            return JsonResponse({'error': 'Exhibition application cannot be canceled at this stage'}, status=400)

        # 删除包含的展台申请关联的展位
        for booth in exhibition.booths.all():
            cancel_booth(request, booth.id)

        # 删除全部的展位申请关联的sectors
        for sector in exhibition.sectors.all():
            sector.delete()
        # TODO 锁定全部的资源
        return JsonResponse({'success': 'Exhibition application canceled successfully!'}, status=200)
    else:
        return HttpResponseNotAllowed(['POST'])

templates/System/copilot.html
{% extends 'Public/base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}
{% load markdown_extras %}

{% block extra_head %}
    <title>Watson</title>
    <link rel="stylesheet" href="{% static 'css/System/copilot.css' %}">
{% endblock %}

{% block extra_nav_icons %}
    <!-- Additional icons in the navigation bar -->
    {% if user.is_authenticated and user_type == 'Manager' %}
        <li class="nav-item">
            <a class="nav-link mt-3" href="{% url 'Statistic:statistic' %}"><i class="fas fa-chart-bar fa-lg"></i></a>
        </li>
        <li class="nav-item">
            <a class="nav-link mt-3" href="{% url 'Layout:layout' %}"><i class="fas fa-edit fa-lg"></i></a>
        </li>
    {% endif %}
{% endblock %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'Venue:home' %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Watson Copilot</li>
        </ol>
    </nav>
{% endblock %}

{% block content %}
    <!-- Modal for LLM Warning -->
    <div class="modal fade" id="warningModal" tabindex="-1" aria-labelledby="warningModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="warningModalLabel">Note</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Watson Copilot is powered by LLM technology from OpenAI. 
                    While we strive for accuracy, the responses can be imperfect. 
                    Always verify critical information independently.

                    The LLM is prompt-engineered to provide answers only relevant to the Mrs. Hudson system. 
                    Please do not use the model for any other purposes. 
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Okay</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal for "Delete History" -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Confirm Delete</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete all conversation history?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <form method="post" action="{% url 'System:delete_all_conversation_history' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal for Loading Answer -->
    <div class="modal" id="loadingModal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-body text-center">
                    <div class="loading-spinner"></div>
                    <p class="mt-3">Loading answer. Please wait for a while...</p>
                </div>
            </div>
        </div>
    </div>

    <div class="container mt-4">
        
        <div class="chat-container">
            <div class="chat-header">
                <h1 class="logo-title">Watson Copilot</h1>
            </div>

            

            <!-- Chat Messages -->
            <div class="chat-box">
                {% if error %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                {% endif %}
                {% for conversation in conversation_history %}
                    <div class="chat-message">
                        <div class="chat-message-header">
                            <strong><i>[{{ conversation.timestamp }}]</i></strong>
                        </div>
                        <div class="chat-message-body">
                            <p>
                                <img src="{% static 'images/System/user-avatar.jpg' %}" alt="User" class="chat-avatar">
                                <strong>You:</strong>
                                {{ conversation.user_input|markdown|safe }}
                            </p>
                            <p>
                                <img src="{% static 'images/System/watson-avatar.jpg' %}" alt="Watson" class="chat-avatar">
                                <strong>Watson:</strong>
                                {{ conversation.copilot_response|markdown|safe }}
                            </p>
                        </div>
                    </div>
                {% endfor %}
            </div>

            <!-- Input Form -->
            <div class="chat-input">
                <form method="post">
                    {% csrf_token %}
                    <textarea name="user_input" class="form-control" rows="3" placeholder="Type your question here..."></textarea>
                    <div class="d-flex justify-content-between mt-3">
                        <div>
                            <button type="submit" class="btn btn-success" id="askWatsonButton">Ask Watson</button>
                            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete History</button>
                        </div>
                        <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#warningModal">?</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script>
        document.getElementById('askWatsonButton').addEventListener('click', function() {
            $('#loadingModal').modal('show');
            // Automatically hide the modal after 60 seconds
            setTimeout(function() {
                $('#loadingModal').modal('hide');
            }, 60000);
        });
    </script>
{% endblock %}