COMP3030J_Hudson/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from django.views.generic import RedirectView
from Inventory.views import *
from Layout.views import *
from Statistic.views import *
from System.views import *
from User.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# 当settings.py的DEBUG为True时, handler404不会生效, 因为Django要暴露错误信息以方便开发者调试
handler404 = 'System.views.custom_404_interceptor'  # 该行代码用于无效页面的重定向

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='User:welcome', permanent=False)),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('Inventory/', include(('Inventory.urls', 'Inventory'), namespace='Inventory')),
    path('Layout/', include(('Layout.urls', 'Layout'), namespace='Layout')),
    path('Statistic/', include(('Statistic.urls', 'Statistic'), namespace='Statistic')),
    path('System/', include(('System.urls', 'System'), namespace='System')),
    path('User/', include(('User.urls', 'User'), namespace='User')),
    path('Venue/', include(('Venue.urls', 'Venue'), namespace='Venue')),
    path('Exhibition/', include(('Exhibition.urls', 'Exhibition'), namespace='Exhibition')),
    path('Booth/', include(('Booth.urls', 'Booth'), namespace='Booth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 添加data/的url映射
    urlpatterns += staticfiles_urlpatterns()  # 添加static/的url映射

System/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('copilot/', views.copilot, name='copilot'),
    path('delete_all_conversation_history/', views.delete_all_conversation_history, name='delete_all_conversation_history'),

]

User/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('welcome/', views.welcome, name='welcome'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('message/', views.view_message, name='view_message'),
    path('message/detail/<int:message_id>/', views.view_message_detail, name='view_message_detail'),
    path('message/reply_message/<int:message_id>/', views.reply_message, name='reply_message'),
    path('application/detail/<str:application_type>/<int:application_id>/',
         views.view_application_detail, name='view_application_detail'),
    path('application/reject_application/<str:application_type>/<int:application_id>/',
         views.reject_application, name='reject_application'),
    path('application/accept_application/<str:application_type>/<int:application_id>/',
         views.accept_application, name='accept_application'),
]

templates/Public/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'images/Public/hudson_icon.png' %}" type="image/png">
    <!-- 导入bootstrap的css,icon和js -->
    <link href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/5.2.3/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
    <script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/5.2.3/js/bootstrap.bundle.min.js"></script>
    <!-- 导入google字体 -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
    <!-- 导入jquery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- 导入axios -->
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <!-- 导入font-awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <!-- 导入 Material Icons 字体 -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
    <!-- 导入vue2 -->
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.min.js"></script>
    <!-- 导入konva.js -->
    <script src="https://unpkg.com/konva@9/konva.min.js"></script>
    <!-- 导入chart.js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.2/dist/chart.umd.min.js"></script>
    <!-- 导入静态资源 -->
    <link rel="stylesheet" href="{% static 'css/Public/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/Public/sidebar.css' %}">
    <script src="{% static 'js/Public/base.js' %}"></script>
    {% block extra_head %}
        <!-- 在这里添加额外的head内容 -->
    {% endblock %}
</head>


<body>
{#隐藏的csrf_token，在其他页面中不再需要添加csrf_token#}
<input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">

<div id="main-wrapper">

    <!-- 导航栏 -->
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'User:welcome' %}">
                <img id="logo-image" src="{% static 'images/Public/hudson.png' %}" alt="Hudson Logo"
                     style="height: 45px; margin-right: 10px; margin-top: -10px">
                Mrs. Hudson
            </a>

            <div class="breadcrumb-container">
                {% block breadcrumbs %}
                    <!-- 面包屑导航 -->
                {% endblock %}
            </div>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item me-2">
                        <a class="nav-link" href="#" id="theme-toggle" title="Theme"><i
                                class="fas fa-moon fa-lg"></i></a>
                    </li>

                    {% block extra_nav_icons %}
                        <!-- 在这里添加额外的icon-->
                    {% endblock %}
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link me-2" href="{% url 'System:copilot' %}"><i class="fas fa-robot fa-lg"
                                                                                          title="Watson Copilot"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link me-2" href="{% url 'User:view_message' %}" title="Message"><i
                                    class="fas fa-envelope fa-lg"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link me-2" href="{% url 'User:logout' %}" title="Logout"><i
                                    class="fas fa-sign-out-alt fa-lg"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link me-2" href="{% url 'User:profile' %}" title="Profile"><i
                                    class="fas fa-user fa-lg"></i></a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link me-2" href="{% url 'User:login' %}" title="Login"><i
                                    class="fas fa-sign-in-alt fa-lg"></i></a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <!-- 消息提醒(Toast) -->
    <div id="toast-container" class="toast-container position-fixed top-0 start-50 translate-middle-x p-3">
        {% for message in messages %}
            <div class="toast-message" data-message="{{ message }}" data-tag="{{ message.tags }}"
                 style="display: none;"></div>
        {% endfor %}
    </div>


    <!-- 滚动到顶部按钮 -->
    <div id="scroll-detector"></div>
    <button id="scroll-to-top" class="btn btn-success rounded-circle shadow">
        <i class="fas fa-arrow-up"></i>
    </button>


    <!-- 页面主体内容 -->
    <div class="public-base-main-content container-fluid px-0">
        <div class="row g-0"><!-- 添加 g-0 移除格子间距 -->
            <div class="d-flex">
                <div class="public-base-sidebar" id="sidebar">
                    {% block sidebar %}
                        <!-- 侧边栏内容 -->
                    {% endblock %}
                </div>
                <div class="public-base-main-content" id="content">
                    {% block content %}
                        <!-- 页面主体内容 -->
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>

    <!-- 底边栏 -->
    <footer class="public-base-footer text-center">
        <div class="text-center p-3">
            <img src="{% static 'images/Public/bjut.png' %}" alt="BJUT Logo" style="height: 50px;">
            © 2024 Mrs. H.U.D.S.O.N. <i>Holistic Utility Deployment & Sustainability Overseeing Network.</i> All rights
            reserved.
            <img src="{% static 'images/Public/ucd.png' %}" alt="UCD Logo" style="height: 50px;">
            <br>
        </div>
    </footer>
</div>


<script>
    // 获取logo图片
    const logoImage = document.getElementById('logo-image');

    // 获取并监听当前主题
    const themeToggle = document.getElementById('theme-toggle');
    themeToggle.addEventListener('click', function () {
        const currentTheme = document.body.classList.contains('dark-mode') ? 'dark-mode' : 'light-mode';
        const newTheme = currentTheme === 'dark-mode' ? 'light-mode' : 'dark-mode';
        localStorage.setItem('theme', newTheme); // 保存用户偏好
        toggleTheme(newTheme);
        themeToggle.blur();
    });

    document.addEventListener('DOMContentLoaded', () => {
        // 执行切换主题
        toggleTheme();

        // 执行滚动到顶部
        scrollToTop();
    });

    // 切换主题并更新元素
    function toggleTheme() {
        const theme = localStorage.getItem('theme') || 'light-mode';
        document.body.classList.toggle('dark-mode', theme === 'dark-mode');

        const icon = themeToggle.querySelector('i');
        if (theme === 'dark-mode') {
            icon.classList.remove('fa-moon');
            icon.classList.add('fa-sun');
            logoImage.src = "{% static 'images/Public/hudson_dark.png' %}";
        } else {
            icon.classList.remove('fa-sun');
            icon.classList.add('fa-moon');
            logoImage.src = "{% static 'images/Public/hudson.png' %}";
        }

        // 同步切换所有以 .nav 开头的类
        document.querySelectorAll('[class*="nav"]').forEach(el => {
            el.classList.forEach(className => {
                if (className.startsWith('nav')) {
                    el.classList.toggle('dark-mode', theme === 'dark-mode');
                }
            });
        });

        // 同步切换所有以 .table 开头的类
        document.querySelectorAll('[class*="table"]').forEach(el => {
            el.classList.forEach(className => {
                if (className.startsWith('table')) {
                    el.classList.toggle('dark-mode', theme === 'dark-mode');
                }
            });
        });

        // 同步切换所有以 .card 开头的类
        document.querySelectorAll('[class*="card"]').forEach(el => {
            el.classList.forEach(className => {
                if (className.startsWith('card')) {
                    el.classList.toggle('dark-mode', theme === 'dark-mode');
                }
            });
        });

        // 同步切换所有以 .chat-container 开头的类 (针对Copilot页面)
        document.querySelectorAll('[class*="chat-container"]').forEach(el => {
            el.classList.forEach(className => {
                if (className.startsWith('chat-container')) {
                    el.classList.toggle('dark-mode', theme === 'dark-mode');
                }
            });
        });

        // 同步切换所有以 .chat-box 开头的类 (针对Copilot页面)
        document.querySelectorAll('[class*="chat-box"]').forEach(el => {
            el.classList.forEach(className => {
                if (className.startsWith('chat-box')) {
                    el.classList.toggle('dark-mode', theme === 'dark-mode');
                }
            });
        });

        // 同步切换所有以 .chat-message 开头的类 (针对Copilot页面)
        document.querySelectorAll('[class*="chat-message"]').forEach(el => {
            el.classList.forEach(className => {
                if (className.startsWith('chat-message')) {
                    el.classList.toggle('dark-mode', theme === 'dark-mode');
                }
            });
        });




        // 切换其他需要的元素
        document.querySelectorAll('.sidebar').forEach(el => el.classList.toggle('dark-mode', theme === 'dark-mode'));
        document.querySelectorAll('.public-base-footer').forEach(el => el.classList.toggle('dark-mode', theme === 'dark-mode'));
        document.querySelectorAll('.logo-title').forEach(el => el.classList.toggle('dark-mode', theme === 'dark-mode'));
        document.querySelectorAll('tr').forEach(el => el.classList.toggle('dark-mode', theme === 'dark-mode'));
        document.querySelectorAll('tbody').forEach(el => el.classList.toggle('dark-mode', theme === 'dark-mode'));
        document.querySelectorAll('.toast').forEach(el => el.classList.toggle('dark-mode', theme === 'dark-mode'));
        {#document.querySelectorAll('.card').forEach(el => el.classList.toggle('dark-mode', theme === 'dark-mode'));#}
    }

    function scrollToTop() {
        const scrollDetector = document.getElementById("scroll-detector");
        const scrollTopButton = document.getElementById("scroll-to-top");

        const observer = new IntersectionObserver((entries) => {
            const entry = entries[0];
            if (!entry.isIntersecting) {
                scrollTopButton.style.display = "flex";
            } else {
                scrollTopButton.style.display = "none";
            }
        });

        observer.observe(scrollDetector);

        scrollTopButton.onclick = function () {
            window.scrollTo({
                top: 0,
                behavior: 'smooth'
            });
        };

        // Optional: Reset scrollTopButton to top if necessary
        scrollTopButton.addEventListener('transitionend', function () {
            if (window.scrollY === 0) {
                scrollTopButton.style.display = "none";
            }
        });
    }

</script>

<!-- 在这里添加额外的脚本 -->
{% block scripts %}

{% endblock %}

</body>
</html>

templates/Public/sidebar.html
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'css/Public/sidebar.css' %}">
    <script src="{% static 'js/Public/sidebar.js' %}"></script>
</head>

<div class="sidebar d-flex flex-column flex-shrink-0 p-3"
     style="width: 240px; height: 100%; min-height: 95vh; /* 边框 */">

    <!-- 侧边栏标题 -->
    <a class="sidebar-title d-flex align-items-center mb-3 mb-md-0 me-md-auto text-decoration-none">
        <span class="fs-4"><strong>{{ page_title }}</strong></span>
    </a>
    <hr>

    <!-- 自定义的侧边栏item列表 -->
    <ul class="nav nav-pills flex-column mb-auto flex-grow-1">
        {% for item in custom_items %}
            {% if item.children %}
                <!-- 有子条目的项 -->
                <li class="nav-item">
                    <a class="nav-link d-flex justify-content-between"
                       data-bs-toggle="collapse" href="#collapse-{{ forloop.counter }}"
                       role="button" aria-expanded="{% if applications_type %}true{% else %}false{% endif %}"
                       aria-controls="collapse-{{ forloop.counter }}">
                        <span><strong>{{ item.name }}</strong></span>
                        <span class="toggle-icon ms-auto"><i
                                class="bi {% if applications_type %}bi-chevron-down{% else %}bi-chevron-right{% endif %}"></i></span>
                    </a>
                    <div class="collapse {% if applications_type %}show{% endif %}" id="collapse-{{ forloop.counter }}">
                        <ul class="nav flex-column ms-3 child-menu">
                            {% for child in item.children %}
                                {% if child is not None %}
                                <li class="nav-item {{ child.active_class }}">
                                    <a href="{{ child.url }}"
                                       class="nav-link {{ child.active_class }}"><strong>{{ child.name }}</strong></a>
                                </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </li>
            {% else %}
                <!-- 没有子条目的项 -->
                <li class="nav-item {{ item.active_class }}">
                    <a href="{{ item.url }}"
                       class="nav-link {{ item.active_class }}"><strong>{{ item.name }}</strong></a>
                </li>
            {% endif %}
        {% endfor %}
    </ul>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const collapsibleLinks = document.querySelectorAll('[data-bs-toggle="collapse"]');
        collapsibleLinks.forEach(link => {
            link.addEventListener('click', function () {
                const icon = link.querySelector('.toggle-icon i'); // 修改为选择 i 标签
                const isCollapsed = icon.classList.toggle('collapsed'); // 切换 collapsed 类
                if (isCollapsed) {
                    icon.classList.remove('bi-chevron-right');
                    icon.classList.add('bi-chevron-down');
                } else {
                    icon.classList.remove('bi-chevron-down');
                    icon.classList.add('bi-chevron-right');
                }
            });
        });
    });
</script>