COMP3030J_Hudson/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from django.views.generic import RedirectView
from Inventory.views import *
from Layout.views import *
from Statistic.views import *
from System.views import *
from User.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# 当settings.py的DEBUG为True时, handler404不会生效, 因为Django要暴露错误信息以方便开发者调试
handler404 = 'System.views.custom_404_interceptor'  # 该行代码用于无效页面的重定向

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='User:welcome', permanent=False)),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('Inventory/', include(('Inventory.urls', 'Inventory'), namespace='Inventory')),
    path('Layout/', include(('Layout.urls', 'Layout'), namespace='Layout')),
    path('Statistic/', include(('Statistic.urls', 'Statistic'), namespace='Statistic')),
    path('System/', include(('System.urls', 'System'), namespace='System')),
    path('User/', include(('User.urls', 'User'), namespace='User')),
    path('Venue/', include(('Venue.urls', 'Venue'), namespace='Venue')),
    path('Exhibition/', include(('Exhibition.urls', 'Exhibition'), namespace='Exhibition')),
    path('Booth/', include(('Booth.urls', 'Booth'), namespace='Booth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 添加data/的url映射
    urlpatterns += staticfiles_urlpatterns()  # 添加static/的url映射

User/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('welcome/', views.welcome, name='welcome'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('message/', views.view_message, name='view_message'),
    path('message/detail/<int:message_id>/', views.view_message_detail, name='view_message_detail'),
    path('message/reply_message/<int:message_id>/', views.reply_message, name='reply_message'),
    path('application/detail/<str:application_type>/<int:application_id>/',
         views.view_application_detail, name='view_application_detail'),
    path('application/reject_application/<str:application_type>/<int:application_id>/',
         views.reject_application, name='reject_application'),
    path('application/accept_application/<str:application_type>/<int:application_id>/',
         views.accept_application, name='accept_application'),
]

User/forms.py
import os

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.conf import settings
from dotenv import load_dotenv

from User.models import GlobalSetting


class RegisterForm(UserCreationForm):
    ACCOUNT_TYPES = [
        ('Manager', 'Manager'),
        ('Organizer', 'Organizer'),
        ('Exhibitor', 'Exhibitor'),
    ]

    email = forms.EmailField(required=True)
    account_type = forms.ChoiceField(choices=ACCOUNT_TYPES)
    authorization_code = forms.CharField(required=False)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2", "account_type")

    def clean_email(self):
        # 获取表单中的email字段
        email = self.cleaned_data.get('email')
        # 检查数据库中是否已经存在该邮箱
        if User.objects.filter(email=email).exists():
            raise ValidationError("A user with that email already exists.")
        return email

    def clean_authorization_code(self):
        account_type = self.cleaned_data.get('account_type')
        authorization_code = self.cleaned_data.get('authorization_code')
        if account_type == 'Manager':
            AUTHORIZATION_CODE = GlobalSetting.objects.get(key='AUTHORIZATION_CODE').value
            if authorization_code != AUTHORIZATION_CODE:
                raise ValidationError("Invalid authorization code for Manager account.")
        return authorization_code

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        if not User.objects.filter(username=username).exists():
            self.add_error('username', 'User does not exist.')
            raise ValidationError("User does not exist.")
        user = User.objects.get(username=username)
        if not user.check_password(password):
            self.add_error('password', 'Incorrect password.')
            raise ValidationError("Incorrect password.")
        return cleaned_data


class ReplyMessageForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'id': 'messageTitle'}), max_length=100)
    content = forms.CharField(widget=forms.Textarea(attrs={'rows': 3, 'id': 'messageContent'}), max_length=1000)

    def clean(self):
        cleaned_data = super(ReplyMessageForm, self).clean()
        title = cleaned_data.get('title')
        content = cleaned_data.get('content')
        if not title:
            self.add_error('title', 'Title cannot be empty.')
            raise ValidationError("Title cannot be empty.")
        if not content:
            self.add_error('content', 'Content cannot be empty.')
            raise ValidationError("Content cannot be empty.")
        return cleaned_data

User/views.py
import json
import os

from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.http import Http404, JsonResponse, HttpResponseNotAllowed
from django.views.decorators.cache import never_cache
from django.shortcuts import render, redirect
from Booth.models import BoothApplication, Booth
from Exhibition.models import ExhibitionApplication, Exhibition
from Inventory.models import ResourceApplication, Item

from .forms import RegisterForm, LoginForm, ReplyMessageForm  # 导入注册和登录表单类
from django.contrib.auth import authenticate, login as auth_login  # 导入认证和登录方法
from .models import *
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages


def welcome(request):  # url: path('welcome/', views.welcome, name='welcome'),
    if request.method == 'GET':
        # get the photosource from the database
        exhibitions = Exhibition.objects.all()
        photo_list = [exhibition.image.url for exhibition in exhibitions]

        return render(request, 'User/welcome.html', {'exhibitions_photos': photo_list})
    else:
        if request.user.is_authenticated:
            return redirect('Venue:home')
        else:
            return redirect('User:login')


def register(request):
    if request.method == 'POST':  # 如果是 POST 请求
        form = RegisterForm(request.POST)  # 使用提交的数据实例化注册表单
        if form.is_valid():  # 如果表单数据有效
            user = form.save()  # 保存用户信息
            user_type = form.cleaned_data.get('account_type')
            if user_type == 'Manager':
                manager = Manager.objects.create(detail=user)
                manager.save()
                user.is_staff = True
                user.is_superuser = True
                user.save()
            elif user_type == 'Organizer':
                organizer = Organizer.objects.create(detail=user)
                organizer.save()
            elif user_type == 'Exhibitor':
                exhibitor = Exhibitor.objects.create(detail=user)
                exhibitor.save()
            messages.success(request, 'Registration successful. You can now log in.')
            return redirect('User:login')  # 重定向到登录页面
    else:
        form = RegisterForm()  # 创建一个空的注册表单
    return render(request, 'User/register.html', {'form': form})  # 渲染注册页面，显示空表单


@never_cache  # 禁用缓存，防止用户未退出登录直接通过浏览器返回按钮访问登录页面
def login(request):
    if request.user.is_authenticated:  # 如果用户已经登录
        return redirect('Venue:home')  # 重定向到主页
    if request.method == 'POST':  # 如果是 POST 请求
        form = LoginForm(request.POST)  # 使用提交的数据实例化登录表单
        if form.is_valid():  # 如果表单数据有效
            username = form.cleaned_data.get('username')  # 获取用户名
            password = form.cleaned_data.get('password')  # 获取密码
            user = authenticate(username=username, password=password)  # 调用认证方法验证用户
            if user is not None:  # 如果用户存在
                auth_login(request, user)  # 将用户存入session
                user_type = 'Manager' if hasattr(request.user, 'manager') \
                    else 'Organizer' if hasattr(request.user, 'organizer') \
                    else 'Exhibitor' if hasattr(request.user, 'exhibitor') \
                    else 'Guest'
                request.session['user_type'] = user_type  # 将user_type存入session
                messages.success(request, 'Login successful. Welcome!')
                return redirect('User:welcome')  # 重定向到欢迎页面
            else:
                # 如果认证失败，将错误信息返回给用户并重新渲染登录页面
                messages.error(request, 'Invalid login credentials.')
    else:
        form = LoginForm()  # 创建一个空的登录表单
    return render(request, 'User/login.html', {'form': form})  # 渲染登录页面，显示空表单


def logout(request):
    request.session.flush()  # 清空session
    messages.success(request, 'You have been logged out.')
    return redirect('User:login')


def profile(request):
    user = request.user

    if request.method == 'GET':
        user_type = 'Manager' if hasattr(user, 'manager') else 'Organizer' if hasattr(user,
                                                                                      'organizer') else 'Exhibitor'

        from django.core.paginator import Paginator

        if user_type == 'Organizer':
            exhibitions = ExhibitionApplication.objects.filter(applicant=user).exclude(
                stage__in=['REJECTED', 'CANCELLED']).order_by(
                'exhibition__start_at')
            paginator = Paginator(exhibitions, 3)
        elif user_type == 'Exhibitor':
            booths = BoothApplication.objects.filter(applicant=user).exclude(
                stage__in=['REJECTED', 'CANCELLED']).order_by('booth__start_at')
            paginator = Paginator(booths, 3)
        else:
            paginator = None

        if paginator:
            page_number = request.GET.get('page')
            page_obj = paginator.get_page(page_number)
        else:
            page_obj = None

        AUTHORIZATION_CODE = GlobalSetting.objects.get(key='AUTHORIZATION_CODE').value
        context = {
            'user': user,
            'user_type': user_type,
            'page_obj': page_obj,
            'authorization_code': AUTHORIZATION_CODE
        }
        return render(request, 'User/profile.html', context)
    else:
        # POST请求处理用户信息更新
        new_username = request.POST.get('username')
        new_email = request.POST.get('email')
        new_authorization_code = request.POST.get('authorization_code')
        new_password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')

        # 检查并更新用户名、邮箱、密码
        if new_username and user.username != new_username:
            if not User.objects.filter(username=new_username).exists():
                user.username = new_username
            else:
                return JsonResponse({'error': 'Username already exists.'}, status=400)

        if new_email and user.email != new_email:
            if not User.objects.filter(email=new_email).exists():
                user.email = new_email
            else:
                return JsonResponse({'error': 'Email already exists.'}, status=400)

        AUTHORIZATION_CODE = GlobalSetting.objects.get(key='AUTHORIZATION_CODE').value
        if new_authorization_code and AUTHORIZATION_CODE != new_authorization_code:
            auth_code = GlobalSetting.objects.get(key='AUTHORIZATION_CODE')
            auth_code.value = new_authorization_code
            auth_code.save()
        else:
            return JsonResponse({'error': 'Authorization Code already exists.'}, status=400)

        if new_password and confirm_password and not check_password(new_password, user.password):
            if new_password == confirm_password:
                user.set_password(new_password)
                update_session_auth_hash(request, user)
            else:
                return JsonResponse({'error': 'Passwords do not match.'}, status=400)

        user.save()
        return JsonResponse({'message': 'Profile updated successfully.'}, status=200)


@login_required
def view_message(request):
    try:
        # 消息类型默认为 'unread', 申请类型默认为 'exhibition'
        item_type = request.GET.get('item_type', 'unread')
        applications_type = request.GET.get('applications_type', '')
        # 根据请求的消息类型进行查询
        if item_type == 'unread':
            items = Message.objects.filter(recipient=request.user, is_read=False).order_by('-created_at')
        elif item_type == 'inbox':
            items = Message.objects.filter(recipient=request.user).order_by('-created_at')
        elif item_type == 'sent':
            items = Message.objects.filter(sender=request.user).order_by('-created_at')
        # 根据请求的申请类型进行查询
        elif item_type == 'applications':
            if applications_type == 'exhibition':
                if hasattr(request.user, 'manager'):
                    items = ExhibitionApplication.objects.all().order_by('exhibition__start_at')
                elif hasattr(request.user, 'organizer'):
                    items = ExhibitionApplication.objects.filter(applicant=request.user).order_by(
                        'exhibition__start_at')
                else:
                    return Http404("Permission denied")
            elif applications_type == 'booth':
                if hasattr(request.user, 'manager'):
                    items = BoothApplication.objects.all().order_by('booth__start_at')
                elif hasattr(request.user, 'exhibitor'):
                    items = BoothApplication.objects.filter(applicant=request.user).order_by('booth__start_at')
                else:
                    raise Http404("Permission denied")
            elif applications_type == 'resource':
                if hasattr(request.user, 'manager'):
                    items = ResourceApplication.objects.all().order_by('booth__start_at')
                elif hasattr(request.user, 'exhibitor'):
                    items = ResourceApplication.objects.filter(applicant=request.user).order_by('booth__start_at')
                else:
                    raise Http404("Permission denied")
            else:
                raise Http404("Application type not found")
        else:
            raise Http404("Message type not found")
        # 设置分页
        paginator = Paginator(items, 10)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        # 自定义侧边栏链接
        custom_items = [
            {'name': '📬 Unread', 'url': '?item_type=unread',
             'active_class': 'active' if item_type == 'unread' else '',
             'children': []},
            {'name': '📪 Inbox', 'url': '?item_type=inbox',
             'active_class': 'active' if item_type == 'inbox' else '',
             'children': []},
            {'name': '📤 Sent', 'url': '?item_type=sent',
             'active_class': 'active' if item_type == 'sent' else '',

templates/User/info.html
{% extends "Public/base.html" %}

{% block extra_head %}
    <title>Hudson Resource Management System</title>
{% endblock %}

{% block content %}
    {#用户信息界面#}
    
{% endblock %}

{% block scripts %}

{% endblock %}

templates/User/login.html
{% extends "Public/base.html" %}
{% load static %}

{% block extra_head %}
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/User/login.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2 class="login-title mb-3">Login</h2>
                <form action="{% url 'User:login' %}" method="post" class="needs-validation" novalidate>
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="username" class="form-label">User Name:</label>
                        <input type="text" class="form-control" id="username" name="username" required>
                        {% if form.username.errors %}
                            <div class="alert alert-danger">
                                {{ form.username.errors.0 }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Password:</label>
                        <input type="password" class="form-control" id="password" name="password" required>
                        {% if form.password.errors %}
                            <div class="alert alert-danger">
                                {{ form.password.errors.0 }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary">Login</button>
                    </div>
                </form>

                <p>Don't have an account? <a href="{% url 'User:register' %}">Register</a></p>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {# 如果需要添加脚本，可在这里加入相应的 <script> 标签 #}
{% endblock %}

templates/User/register.html
{% extends "Public/base.html" %}
{% load static %}

{% block extra_head %}
    <title>Register</title>
    <link rel="stylesheet" href="{% static 'css/User/register.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2 class="register-title mb-3">Register</h2>
                <form action="{% url 'User:register' %}" method="post" novalidate>
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="username" class="form-label">Username:</label>
                        <input type="text" class="form-control" id="username" name="username" required>
                        {% if form.username.errors %}
                            <div class="alert alert-danger">
                                {{ form.username.errors.0 }}
                            </div>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        <label for="email" class="form-label">Email:</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                        {% if form.email.errors %}
                            <div class="alert alert-danger">
                                {{ form.email.errors.0 }}
                            </div>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        <label for="account_type" class="form-label">Account Type:</label>
                        <select name="account_type" id="account_type" class="form-control" required>
                            <option value="" selected disabled>Select Account Type</option>
                            <option value="Organizer">Organizer</option>
                            <option value="Exhibitor">Exhibitor</option>
                            <option value="Manager">Manager</option>
                        </select>
                        {% if form.authorization_code.errors %}
                            <div class="alert alert-danger">
                                {{ form.authorization_code.errors.0 }}
                            </div>
                        {% endif %}
                    </div>

                    <div class="form-group" id="auth-code-group" style="display:none;">
                        <label for="authorization_code" class="form-label">Authorization Code:</label>
                        <input type="text" class="form-control" id="authorization_code" name="authorization_code">
                    </div>

                    <div class="form-group">
                        <label for="password1" class="form-label">Password:</label>
                        <input type="password" class="form-control" id="password1" name="password1" required>
                        {% if form.password1.errors %}
                            <div class="alert alert-danger">
                                {{ form.password1.errors.0 }}
                            </div>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        <label for="password2" class="form-label">Password Confirmation:</label>
                        <input type="password" class="form-control" id="password2" name="password2" required>
                        {% if form.password2.errors %}
                            <div class="alert alert-danger">
                                {{ form.password2.errors.0 }}
                            </div>
                        {% endif %}
                    </div>
                
                    <div class="form-group">
                        <a href="{% url 'User:login' %}" class="btn btn-link">Already have an account? Log in</a>
                    </div>
                
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Register</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        document.getElementById('account_type').addEventListener('change', function () {
            var authCodeGroup = document.getElementById('auth-code-group');
            if (this.value === 'Manager') {
                authCodeGroup.style.display = 'block';
            } else {
                authCodeGroup.style.display = 'none';
            }
        });
    </script>
{% endblock %}

templates/User/welcome.html
{% extends 'Public/base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}

{% block extra_head %}
    <title>Welcome</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/User/welcome.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="text-center my-4">
            <h1 class="platform-title">Welcome to Mrs. Hudson!</h1>
        </div>

        <div class="welcome-section">
            <!-- Carousel Start -->
            <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-indicators">
                    {% for photo in exhibitions_photos %}
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %} aria-current="true" aria-label="Slide {{ forloop.counter }}"></button>
                    {% endfor %}
                </div>
                <div class="carousel-inner">
                    {% for photo in exhibitions_photos %}
                        <div class="carousel-item {% if forloop.first %}active{% endif %} carousel-image">
                            <img src="{{ photo }}" class="d-block w-100" alt="Exhibition Photo">
                        </div>
                    {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
            <!-- Carousel End -->

            <div class="row align-items-center mb-5">
                <div class="col-md-6">
                    <img src="{% static 'images/User/1.png' %}" alt="Manage Your: Venue & Exhibition & Booth" class="img-fluid">
                </div>
                <div class="col-md-6">
                    <div class="card shadow-lg p-3 mb-5 rounded">
                        <h1>Manage Your:</h1>
                        <h1>Venue & Exhibition & Booth</h1>
                        <p style="font-size: 1.3em; color: #607180;">Welcome to the Mrs. Hudson Online Resource Management Platform.
                            We are committed to providing comprehensive, convenient, and efficient venue management services
                            for Holmes Company's exhibitions and conferences.</p>
                        <p style="font-size: 1.3em; color: #607180;">Our platform helps you with venue reservations, resource
                            management, and dynamic layout adjustments, ensuring the smooth progress of your exhibitions
                            with maximal resource utilization.</p>
                        <form action="{% url 'User:welcome' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary btn-custom">Get Started!</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="row align-items-center mb-5">
                <div class="col-md-6 order-md-2">
                    <img src="{% static 'images/User/2.png' %}" alt="Venue" class="img-fluid">
                </div>
                <div class="col-md-6 order-md-1">
                    <div class="card shadow-lg p-3 mb-5 rounded">
                        <h1><i class="fas fa-building"></i> Venue</h1>
                        <ul style="font-size: 1.3em; color: #607180;">
                            <li>Add, delete, or modify venue information</li>
                            <li>Customize venue layouts to accommodate different event needs</li>
                            <li>Approve various venue usage requests</li>
                            <li>Manage venue inventory to avoid duplicate purchases and waste</li>
                            <li>Monitor the usage status and attributes of equipment within the venue</li>
                            <li>View statistical data of venue usage</li>
                            <li>Dynamic prediction of crowd flow</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row align-items-center mb-5">
                <div class="col-md-6">
                    <img src="{% static 'images/User/3.png' %}" alt="Exhibition" class="img-fluid">
                </div>
                <div class="col-md-6">
                    <div class="card shadow-lg p-3 mb-5 rounded">
                        <h1><i class="fas fa-paint-brush"></i> Exhibition</h1>
                        <ul style="font-size: 1.3em; color: #607180;">
                            <li>Apply for, delete, or modify exhibitions</li>
                            <li>Customize exhibition layouts to optimize exhibition effectiveness</li>
                            <li>Approve various exhibition requests</li>
                            <li>Manage exhibition inventory to ensure adequate supplies</li>
                            <li>Monitor the usage status and attributes of equipment within the exhibition</li>
                            <li>Return borrowed resources to ensure sustainable resource utilization</li>
                            <li>Report damaged items for timely maintenance</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row align-items-center mb-5">
                <div class="col-md-6 order-md-2">
                    <img src="{% static 'images/User/4.png' %}" alt="Booth" class="img-fluid">
                </div>
                <div class="col-md-6 order-md-1">
                    <div class="card shadow-lg p-3 mb-5 rounded">
                        <h1><i class="fas fa-store"></i> Booth</h1>
                        <ul style="font-size: 1.3em; color: #607180;">
                            <li>Apply for, delete, or modify exhibition booths</li>
                            <li>Customize exhibition booth layouts to attract more attendees</li>
                            <li>Manage exhibition booth inventory to showcase the latest products</li>
                            <li>Monitor the usage status and attributes of equipment within the exhibition booth</li>
                            <li>Return borrowed resources to ensure resource recycling</li>
                            <li>Report damaged items for timely maintenance</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row align-items-center">
                <div class="col-md-6">
                    <img src="{% static 'images/User/5.png' %}" alt="Feature" class="img-fluid">
                </div>
                <div class="col-md-6">
                    <div class="card shadow-lg p-3 mb-5 rounded">
                        <h1 ><i class="fas fa-lightbulb"></i> Feature</h1>
                        <ul style="font-size: 1.3em; color: #607180;">
                            <li><b>2D Layout Design:</b> A simple and intuitive layout design tool to help you quickly
                                complete the layout design of venues, exhibitions, and exhibition booths
                            </li>
                            <li><b>AI Assistant:</b> An intelligent customer service system to answer your questions
                                anytime, improving management efficiency
                            </li>
                            <li><b>Real-time Statistics:</b> Detailed statistical data to help you understand resource usage
                                and event effectiveness
                            </li>
                            <li><b>Dynamic Adjustment:</b> Automatically adjust lighting, air conditioning, and water
                                resource usage according to actual needs, saving costs and protecting the environment
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <!-- Bootstrap Carousel JavaScript -->
    <script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/5.2.3/js/bootstrap.bundle.min.js"></script>
{% endblock %}